#!/bin/sh
# Here is the minimal initalization for busybox
# It was designed to be overrided by other packages.

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N

umask 022
export PATH runlevel prevlevel

# fixme: should use devtmpfs instead of tmpfs for /dev.
mount -t tmpfs devtmpfs /dev
cp -a /lib/udev/devices/* /dev/

/bin/mount -a
mdev -s

if [ ! -e /dev/tty2 ]; then ln -sf /dev/null /dev/tty2; fi
if [ ! -e /dev/tty3 ]; then ln -sf /dev/null /dev/tty3; fi
if [ ! -e /dev/tty4 ]; then ln -sf /dev/null /dev/tty4; fi

# optional
trap ":" INT QUIT TSTP

# optional
for i in /etc/rc.d/rcS.d/S??*
do
	# Ignore dangling symlinks for now.
	[ ! -f "$i" ] && continue
	#echo $i
	case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set start
				. $i
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			$i start
			;;
	esac
done

# optional
[ -x /etc/rc.d/rc.local ] && /etc/rc.d/rc.local

