#!/bin/sh
# Copyright (C) 2012 WonderMedia Technologies, Inc. All rights reserved.

for dir in dev bin opt var home root lib mnt sys sbin tmp etc proc media usr boot; do
	if [ ! -e $dir ]; then
		mkdir -p $dir
	fi
done

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

if [ ! -e /lib/udev/devices/null ]; then

	/bin/mkdir -p /var/run

	/bin/mkdir -p /lib/udev/devices/shm
	/bin/mkdir -p /lib/udev/devices/pts
	/bin/mkdir -p /lib/udev/devices/net

	/bin/mkdir -p /etc/network/if-pre-up.d
	/bin/mkdir -p /etc/network/if-post-down.d
	/bin/mkdir -p /etc/network/if-down.d
	/bin/mkdir -p /etc/network/if-up.d
	/bin/mkdir -p /etc/init.d
	/bin/mkdir -p /etc/rc.d/rc0.d
	/bin/mkdir -p /etc/rc.d/rcS.d
	/bin/mkdir -p /etc/udev/rules.d
	/bin/mkdir -p /etc/udev/scripts

	/bin/mkdir -p /usr/bin
	/bin/mkdir -p /usr/lib
	/bin/mkdir -p /usr/share/doc
	/bin/mkdir -p /usr/share/udhcpc
	/bin/mkdir -p /usr/sbin
	/bin/mkdir -p /boot

	/bin/mknod /dev/null c 1 3
	#/bin/mknod /dev/console c 5 1

	/bin/mknod /lib/udev/devices/null c 1 3
	/bin/mknod /lib/udev/devices/zero c 1 5
	/bin/mknod /lib/udev/devices/kmsg c 1 11
	/bin/mknod /lib/udev/devices/tty0 c 4 0
	/bin/mknod /lib/udev/devices/tty1 c 4 1
	/bin/mknod /lib/udev/devices/tty c 5 0
	/bin/mknod /lib/udev/devices/console c 5 1
	/bin/mknod /lib/udev/devices/ptmx c 5 2
	/bin/mknod /lib/udev/devices/lp0 c 6 0
	/bin/mknod /lib/udev/devices/net/tun c 10 200
	/bin/mknod /lib/udev/devices/ppp c 108 0

	/bin/ln -s /proc/kcore     /lib/udev/devices/core
	/bin/ln -s /proc/self/fd   /lib/udev/devices/fd
	/bin/ln -s /proc/self/fd/0 /lib/udev/devices/stdin
	/bin/ln -s /proc/self/fd/1 /lib/udev/devices/stdout
	/bin/ln -s /proc/self/fd/2 /lib/udev/devices/stderr
fi

exec /sbin/init
