#!/bin/sh

run_bspinst ()
{
        local tstart=`date +"%s"`
        local tend=
        local tnow=
        local quit=0

        let "tend = tstart + $1"
        tnow=`date +"%s"`

        while [ $tnow -lt $tend ]; do
                for dir in `find /mnt -maxdepth 1`; do
                        if [ -d ${dir}/bspinst ]; then
                                /usr/bin/bspinst.sh
                                quit=1
                        fi
                done
                if [ $quit -eq 1 ]; then
                        break
                fi
                tnow=`date +"%s"`
                sleep 1
        done
}

run_bspinst 5 &

